### PR TITLE
new login/register pages

### PR DESCRIPTION
**Pull request by travis**

### CODE REVIEW

**Comment by ianconsolata** [comment]
This PR is failing because of https://nextjs.org/docs/messages/failed-loading-swc. I've gotten this a couple times before on my PRs, and rebuilding got it to go away. Do you have any idea what may be causing it or how to fix it?

**Comment by travis** [comment]
@ianconsolata no not sure what that is and didn't go away on rebuild this time - I had to resort to an entirely new branch:

https://github.com/mysilio-co/garden/pull/106

really puzzling, only thing I can figure is something weird in the package-lock.json because I tried removing various parts that I thought might be the culprit but had no luck

**Comment by ianconsolata** [comment]
Weird, so closing this in favor of #106?

**Comment by travis** [comment]
that's right yep

**Pull request closed without merging**
